# Comparing Scenarios on `premise` Data

`TimexLCASettings` holds everything one calculation needs - the demand, the
method, the background selection, and every timeline/LCI/LCIA option - so one
object is also the record of what was run. `TimexLCA(...).run()`
executes it, `run()` can be called again with overrides, and
`TimexLCA.compare()` runs a list of them into one table.

We follow that through on a real prospective background, from an empty
project to a scenario comparison: build ecoinvent 3.12 (cutoff) plus REMIND-EU databases for 2020-2040 with
[premise](https://github.com/polca/premise), point a small electric-vehicle
foreground at them, and compare EV impacts 1) depending on the year it is
bought and 2) depending on the scenario.

## Setting up the databases

We start totally from scratch, in am empty project:

In [1]:
import bw2data as bd

bd.projects.set_current("my_new_timex_project")
list(bd.databases)

[]

We can download the ecoinvent database and create scenario-copies of it with `premise` through our `ensure_scenario_databases` helper function. Running this requires a premise key (to be asked from `premise` maintainers) and valid ecoinvent credentials. These can be set as environment variables (`PREMISE_KEY`, `ECOINVENT_USERNAME`, `ECOINVENT_PASSWORD`) or passed to the function directly.

In [2]:
from bw_timex import ensure_scenario_databases

database_dates = ensure_scenario_databases(
    {
        "iam_model": "remind-eu",
        "pathway": "SSP2-PkBudg650",
        "system_model": "cutoff",
        "ecoinvent_version": "3.12",
        "years": [2020, 2030, 2040],
    },
    # premise_key="dummy_premise_decryption_key",
    # ecoinvent_credentials=("dummy_user", "dummy_password"),
)

2026-08-26 08:21:05.283 | INFO     | bw_timex.scenario_builder:_resolve_source_database:289 - No database 'ecoinvent-3.12-cutoff' in this project. Importing ecoinvent 3.12 (cutoff) first; this takes a while and needs an ecoinvent licence.

08:21:05+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
Applying strategy: normalize_units
Applying strategy: drop_unspecified_subcategories
Applying strategy: ensure_categories_are_tuples
Applied 3 strategies in 0.00 seconds
Graph statistics for `ecoinvent-3.12-biosphere` importer:
9850 graph nodes:
	emission: 9477
	natural resource: 353
	inventory indicator: 15
	economic: 5
0 graph edges:
0 edges to the following databases:
0 unique unlinked edges (0 total):

100%|██████████| 9850/9850 [00:00<00:00, 55672.35it/s]

08:21:12+0200 [info     ] Vacuuming database

Created database: ecoinvent-3.12-biosphere
Extracting XML data from 26533 datasets
08:21:16+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:21:16+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:21:16+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:21:16+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:21:16+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:21:16+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:21:16+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:21:16+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:21:16+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:21:16+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:21:43+0200 [info     ] Extracted 26533 datasets in 30.61 seconds
Applying strategy: normalize_units
Applying strategy: update_ecoinvent_locations
Applying strategy: remove_zero_amount_coproducts
Applying strategy: remove_zero_amount_inputs_with_no_activity
Applying strategy: remove_unnamed_parameters
Applying strategy: es2_assign_only_product_with_amount_as_reference_product
Applying strategy: assign_single_product_as_activity
Applying strategy: create_composite_code
Applying strategy: drop_unspecified_subcategories
Applying strategy: fix_ecoinvent_flows_pre35
Applying strategy: drop_temporary_outdated_biosphere_flows
Applying strategy: link_biosphere_by_flow_uuid
Applying strategy: link_internal_technosphere_by_composite_code
Applying strategy: delete_exchanges_missing_activity
Applying strategy: delete_ghost_exchanges
Applying strategy: remove_uncertainty_from_negative_loss_exchanges
Applying strategy: fix_unreasonably_high_lognormal_uncertainties
Applying strategy: convert_activity_parameters_to_list
Applying strategy: add_cpc_classification_from_single_reference_product
Applying strategy: delete_none_synonyms
Applying strategy: update_social_flows_in_older_consequential
Applying strategy: set_lognormal_loc_value
Applied 22 strategies in 4.70 seconds
Graph statistics for `ecoinvent-3.12-cutoff` importer:
26533 graph nodes:
	process: 26533
892943 graph edges:
	biosphere: 553892
	technosphere: 312518
	production: 26533
892943 edges to the following databases:
	ecoinvent-3.12-biosphere: 553892
	ecoinvent-3.12-cutoff: 339051
0 unique unlinked edges (0 total):


08:21:48+0200 [warning  ] Not able to determine geocollections for all datasets. This database is not ready for regionalization.

100%|██████████| 26533/26533 [00:34<00:00, 758.55it/s]

08:22:24+0200 [info     ] Vacuuming database
Created database: ecoinvent-3.12-cutoff

2026-08-26 08:24:47.619 | INFO     | bw_timex.scenario_builder:ensure_scenario_databases:380 - Building 3 background database(s) for year(s) [2020, 2030, 2040] with premise (remind-eu, SSP2-PkBudg650, all sectors). Each is a full copy of ecoinvent, so expect tens of minutes and roughly 2-4 GB per year.

premise v.(2, 4, 9, 2)
+------------------------------------------------------------------+
| Warning                                                          |
+------------------------------------------------------------------+
| Because some of the scenarios can yield LCI databases            |
| containing net negative emission technologies (NET),             |
| it is advised to account for biogenic CO2 flows when calculating |
| Global Warming potential indicators.                             |
| `premise_gwp` provides characterization factors for such flows.  |
| It also provides factors for hydrogen emissions to air.          |
|                                                                  |
| Within your Brightway project:                                   |
| from premise_gwp import add_premise_gwp                          |
| add_premise_gwp()                                                |
+------------------------------------------------------------------+
+--------------------------------+----------------------------------+
| Utils functions                | Description                      |
+--------------------------------+----------------------------------+
| clear_cache()                  | Clears the cache folder. Useful  |
|                                | when updating `premise`or        |
|                                | encountering issues with         |
|                                | inventories.                     |
| get_regions_definition(model)  | Retrieves the list of countries  |
|                                | for each region of the model.    |
| ndb.NewDatabase(...)           | Generates a summary of the most  |
| ndb.generate_scenario_report() | important scenarios' variables.  |
+--------------------------------+----------------------------------+
Keep uncertainty data?
NewDatabase(..., keep_source_db_uncertainty=True), keep_imports_uncertainty=True)

Hide these messages?
NewDatabase(..., quiet=True)
- Extracting source database
- Extracting inventories
- Fetching IAM data
Found file: remind-eu_SSP2-PkBudg650
Reading remind-eu_SSP2-PkBudg650 as CSV file

/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data_collection.py:196: FutureWarning: In a future version of xarray the default value for join will change from join='outer' to join='exact'. This change will result in the following ValueError: cannot be aligned with join='exact' because index/labels/sizes are not equal along these coordinates (dimensions): 'sector' ('sector',) The recommendation is to set join explicitly for this case.
  arr = xr.concat(list_arrays, dim="pollutant")

The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
+-------------------------------------------------------------+
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
+-------------------------------------------------------------+
Found file: remind-eu_SSP2-PkBudg650
Reading remind-eu_SSP2-PkBudg650 as CSV file
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
+-------------------------------------------------------------+
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
+-------------------------------------------------------------+
Found file: remind-eu_SSP2-PkBudg650
Reading remind-eu_SSP2-PkBudg650 as CSV file
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
+-------------------------------------------------------------+
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
+-------------------------------------------------------------+
Done!

Processing scenarios for all sectors: 100%|█| 3/3 [06:43<00:00, 134.54

Done!

Write new database(s) to Brightway.
Running core export checks...
Minor anomalies found: check the change report.

Brightway database written: ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2020
Running core export checks...
Minor anomalies found: check the change report.

Brightway database written: ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2030
Running core export checks...
Minor anomalies found: check the change report.

Brightway database written: ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2040
Generate scenario report.
Report saved under /Users/timodiepers/Documents/Coding/bw_timex/notebooks/advanced/export/scenario_report.
Generate change report.

2026-08-26 08:35:23.606 | INFO     | bw_timex.scenario_builder:ensure_scenario_databases:424 - Built 3 background database(s).

Report saved under /Users/timodiepers/Documents/Coding/bw_timex/notebooks/advanced/export/change reports/.

We now find the base ecoinvent database as well as the three time-specific premise databases in our project:

In [3]:
list(bd.databases)

['ecoinvent-3.12-biosphere',
 'ecoinvent-3.12-cutoff',
 'ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2020',
 'ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2030',
 'ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2040']

Next, we add a foreground database. We use the same electric vehicle example as in [this teaching notebook](../teaching/ev_walktrough_premise.ipynb), which we can set up like this:

In [4]:
from bw_timex import create_electric_vehicle_example

create_electric_vehicle_example(
    background_database_name="ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2020"
)

2026-08-26 08:35:25.305 | INFO     | bw_timex.utils:add_temporal_distribution_to_exchange:670 - Added temporal distribution to exchange Exchange: 20000.0 kilowatt hour 'market group for electricity, low voltage' (kilowatt hour, GLO, None) to 'driving an electric vehicle' (pkm over ev lifetime, GLO, None).
2026-08-26 08:35:25.309 | INFO     | bw_timex.utils:add_temporal_distribution_to_exchange:670 - Added temporal distribution to exchange Exchange: -280 kilogram 'market for used Li-ion battery' (kilogram, GLO, None) to 'driving an electric vehicle' (pkm over ev lifetime, GLO, None).
2026-08-26 08:35:25.310 | INFO     | bw_timex.utils:create_electric_vehicle_example:1271 - Created electric vehicle example in database 'foreground'.

## Calculating a `TimexLCA` using `TimexLCASetting``

In [5]:
from bw_timex import TimexLCA, TimexLCASettings

settings = TimexLCASettings(
    demand = {("foreground", "driving"): 1},
    method = ("ecoinvent-3.12", "EF v3.1", "climate change", "global warming potential (GWP100)"),
    scenario={
        "iam_model": "remind-eu",
        "pathway": "SSP2-PkBudg650",
    },
    timeline={ # Settings normally going into .build_timeline()
        "starting_datetime": "2028-01-01",
        "graph_traversal": "bfs",
    },
    lci={}, # Settings normally going into .lci()
    lcia={  # Settings normally going into .static_lcia() or .dynamic_lcia()
        "metric": "GWP",
        "time_horizon": 100,
    },
)

In [6]:
tlca = TimexLCA(settings).run()

print("Time-explicit impact:", tlca.dynamic_score, bd.methods[settings.method]["unit"])

2026-08-26 08:35:25.320 | INFO     | bw_timex.timex_lca:__init__:444 - Initializing TimexLCA object...
2026-08-26 08:35:25.342 | INFO     | bw_timex.timex_lca:__init__:533 - Calculating base LCA...
2026-08-26 08:35:25.353 | INFO     | bw_timex.timex_lca:clean_databases:2475 - Reprocessing 1 modified database(s) before calculating: foreground. This can take a while for large databases.
2026-08-26 08:35:25.374 | INFO     | bw_timex.timex_lca:clean_databases:2481 - Done reprocessing modified databases.
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 8.06e+12)
  warnings.warn(msg, UmfpackWarning)
2026-08-26 08:35:26.402 | INFO     | bw_timex.timex_lca:__init__:588 - Collecting node infos...
2026-08-26 08:35:26.446 | INFO     | bw_timex.timex_lca:__init__:603 - Loading node metadata from 4 database(s)...
2026-08-26 08:35:29.312 | INFO     | bw_timex.timex_lca:__init__:648 - TimexLCA initialized.
2026-08-26 08:35:29.313 | INFO     | bw_timex.timex_lca:run:812 - Starting TimexLCA.run() pipeline...
2026-08-26 08:35:29.313 | INFO     | bw_timex.timex_lca:run:819 - Step 1/4: Building timeline...
2026-08-26 08:35:29.315 | INFO     | bw_timex.timex_lca:build_timeline:1251 - No edge filter function provided. Skipping all edges in background databases.
2026-08-26 08:35:34.284 | INFO     | bw_timex.timex_lca:build_timeline:1274 - Creating activity time mapping...
2026-08-26 08:35:34.393 | INFO     | bw_timex.timeline_builder:__init__:119 - Traversing supply chain graph...
2026-08-26 08:35:34.414 | INFO     | bw_timex.timeline_builder:build_timeline:190 - Building timeline...
2026-08-26 08:35:34.515 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:895 - Reference date 2041-01-01 00:00:00 is higher than all provided dates. Data will be taken from the closest lower year.
2026-08-26 08:35:34.519 | INFO     | bw_timex.timex_lca:run:834 - Step 2/4: Calculating LCI...
2026-08-26 08:35:34.928 | INFO     | bw_timex.timex_lca:lci:1440 - Expanding matrices...
2026-08-26 08:35:34.939 | INFO     | bw_timex.timex_lca:lci:1459 - Calculating dynamic inventory...
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 2.24e+13)
  warnings.warn(msg, UmfpackWarning)
2026-08-26 08:35:58.310 | INFO     | bw_timex.timex_lca:run:843 - Step 3/4: Calculating static LCIA...
2026-08-26 08:35:58.447 | INFO     | bw_timex.timex_lca:run:862 - Step 4/4: Calculating dynamic LCIA...
2026-08-26 08:35:58.473 | INFO     | dynamic_characterization.dynamic_characterization:characterize:135 - No custom dynamic characterization functions provided. Using default dynamic             characterization functions. The flows that are characterized are based on the selection                of the initially chosen impact category.
2026-08-26 08:35:58.553 | INFO     | bw_timex.timex_lca:run:873 - TimexLCA.run() completed successfully.

Time-explicit impact: 27329.168393728134 kg CO2-Eq

Another run using the same `TimexLCA` object, overwriting the time horizon setting:

In [7]:
tlca.run(time_horizon=20) # same as tlca.run(lcia={"time_horizon": 20})
print("Time-explicit impact with time horizon 20:", tlca.dynamic_score, bd.methods[settings.method]["unit"])

2026-08-26 08:35:58.569 | INFO     | bw_timex.timex_lca:run:812 - Starting TimexLCA.run() pipeline...
2026-08-26 08:35:58.570 | INFO     | bw_timex.timex_lca:run:819 - Step 1/4: Building timeline...
2026-08-26 08:35:58.573 | INFO     | bw_timex.timex_lca:run:834 - Step 2/4: Calculating LCI...
2026-08-26 08:35:59.049 | INFO     | bw_timex.timex_lca:lci:1440 - Expanding matrices...
2026-08-26 08:35:59.062 | INFO     | bw_timex.timex_lca:lci:1459 - Calculating dynamic inventory...
2026-08-26 08:36:01.198 | INFO     | bw_timex.timex_lca:run:843 - Step 3/4: Calculating static LCIA...
2026-08-26 08:36:01.202 | INFO     | bw_timex.timex_lca:run:862 - Step 4/4: Calculating dynamic LCIA...
2026-08-26 08:36:01.219 | INFO     | dynamic_characterization.dynamic_characterization:characterize:135 - No custom dynamic characterization functions provided. Using default dynamic             characterization functions. The flows that are characterized are based on the selection                of the initially chosen impact category.
2026-08-26 08:36:01.293 | INFO     | bw_timex.timex_lca:run:873 - TimexLCA.run() completed successfully.

Time-explicit impact with time horizon 20: 31108.70858992546 kg CO2-Eq

## Several calculations: `compare()`

To compare different settings even more easily, use the `compare()` function, which takes a list of settings. It returns a `ComparisonResult`
whose `summary` holds one row each - the scores next to every setting that
produced them, so the table is its own record of what was run.

### Compare different purchasing years

In [8]:
from dataclasses import replace

comparison = TimexLCA.compare(
    [
        replace(settings, starting_datetime=f"{year}-06-01", label=f"bought {year}")
        for year in (2020, 2025, 2030)
    ]
)

2026-08-26 08:36:01.299 | INFO     | bw_timex.timex_lca:__init__:444 - Initializing TimexLCA object...
2026-08-26 08:36:01.301 | INFO     | bw_timex.timex_lca:__init__:533 - Calculating base LCA...
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 8.06e+12)
  warnings.warn(msg, UmfpackWarning)
2026-08-26 08:36:02.271 | INFO     | bw_timex.timex_lca:__init__:588 - Collecting node infos...
2026-08-26 08:36:02.327 | INFO     | bw_timex.timex_lca:__init__:603 - Loading node metadata from 4 database(s)...
2026-08-26 08:36:02.430 | INFO     | bw_timex.timex_lca:__init__:648 - TimexLCA initialized.
2026-08-26 08:36:02.431 | INFO     | bw_timex.timex_lca:compare:1022 - Comparison 1/3: bought 2020
2026-08-26 08:36:02.431 | INFO     | bw_timex.timex_lca:run:812 - Starting TimexLCA.run() pipeline...
2026-08-26 08:36:02.432 | INFO     | bw_timex.timex_lca:run:819 - Step 1/4: Building timeline...
2026-08-26 08:36:02.432 | INFO     | bw_timex.timex_lca:build_timeline:1251 - No edge filter function provided. Skipping all edges in background databases.
2026-08-26 08:36:07.027 | INFO     | bw_timex.timex_lca:build_timeline:1274 - Creating activity time mapping...
2026-08-26 08:36:07.120 | INFO     | bw_timex.timeline_builder:__init__:119 - Traversing supply chain graph...
2026-08-26 08:36:07.138 | INFO     | bw_timex.timeline_builder:build_timeline:190 - Building timeline...
2026-08-26 08:36:07.216 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:888 - Reference date 2018-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-08-26 08:36:07.219 | INFO     | bw_timex.timex_lca:run:834 - Step 2/4: Calculating LCI...
2026-08-26 08:36:07.668 | INFO     | bw_timex.timex_lca:lci:1440 - Expanding matrices...
2026-08-26 08:36:07.679 | INFO     | bw_timex.timex_lca:lci:1459 - Calculating dynamic inventory...
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 2.24e+13)
  warnings.warn(msg, UmfpackWarning)
2026-08-26 08:36:18.265 | INFO     | bw_timex.timex_lca:run:843 - Step 3/4: Calculating static LCIA...
2026-08-26 08:36:18.270 | INFO     | bw_timex.timex_lca:run:862 - Step 4/4: Calculating dynamic LCIA...
2026-08-26 08:36:18.295 | INFO     | dynamic_characterization.dynamic_characterization:characterize:135 - No custom dynamic characterization functions provided. Using default dynamic             characterization functions. The flows that are characterized are based on the selection                of the initially chosen impact category.
2026-08-26 08:36:18.397 | INFO     | bw_timex.timex_lca:run:873 - TimexLCA.run() completed successfully.
2026-08-26 08:36:18.398 | INFO     | bw_timex.timex_lca:compare:1022 - Comparison 2/3: bought 2025
2026-08-26 08:36:18.399 | INFO     | bw_timex.timex_lca:run:812 - Starting TimexLCA.run() pipeline...
2026-08-26 08:36:18.400 | INFO     | bw_timex.timex_lca:run:819 - Step 1/4: Building timeline...
2026-08-26 08:36:18.400 | INFO     | bw_timex.timex_lca:build_timeline:1251 - No edge filter function provided. Skipping all edges in background databases.
2026-08-26 08:36:18.401 | INFO     | bw_timex.timex_lca:build_timeline:1274 - Creating activity time mapping...
2026-08-26 08:36:18.639 | INFO     | bw_timex.timeline_builder:__init__:119 - Traversing supply chain graph...
2026-08-26 08:36:18.656 | INFO     | bw_timex.timeline_builder:build_timeline:190 - Building timeline...
2026-08-26 08:36:18.757 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:895 - Reference date 2041-01-01 00:00:00 is higher than all provided dates. Data will be taken from the closest lower year.
2026-08-26 08:36:18.761 | INFO     | bw_timex.timex_lca:run:834 - Step 2/4: Calculating LCI...
2026-08-26 08:36:19.306 | INFO     | bw_timex.timex_lca:lci:1440 - Expanding matrices...
2026-08-26 08:36:19.334 | INFO     | bw_timex.timex_lca:lci:1459 - Calculating dynamic inventory...
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 2.24e+13)
  warnings.warn(msg, UmfpackWarning)
2026-08-26 08:36:23.331 | INFO     | bw_timex.timex_lca:run:843 - Step 3/4: Calculating static LCIA...
2026-08-26 08:36:23.334 | INFO     | bw_timex.timex_lca:run:862 - Step 4/4: Calculating dynamic LCIA...
2026-08-26 08:36:23.358 | INFO     | dynamic_characterization.dynamic_characterization:characterize:135 - No custom dynamic characterization functions provided. Using default dynamic             characterization functions. The flows that are characterized are based on the selection                of the initially chosen impact category.
2026-08-26 08:36:23.442 | INFO     | bw_timex.timex_lca:run:873 - TimexLCA.run() completed successfully.
2026-08-26 08:36:23.442 | INFO     | bw_timex.timex_lca:compare:1022 - Comparison 3/3: bought 2030
2026-08-26 08:36:23.442 | INFO     | bw_timex.timex_lca:run:812 - Starting TimexLCA.run() pipeline...
2026-08-26 08:36:23.443 | INFO     | bw_timex.timex_lca:run:819 - Step 1/4: Building timeline...
2026-08-26 08:36:23.444 | INFO     | bw_timex.timex_lca:build_timeline:1251 - No edge filter function provided. Skipping all edges in background databases.
2026-08-26 08:36:23.444 | INFO     | bw_timex.timex_lca:build_timeline:1274 - Creating activity time mapping...
2026-08-26 08:36:23.549 | INFO     | bw_timex.timeline_builder:__init__:119 - Traversing supply chain graph...
2026-08-26 08:36:23.561 | INFO     | bw_timex.timeline_builder:build_timeline:190 - Building timeline...
2026-08-26 08:36:23.641 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:895 - Reference date 2041-01-01 00:00:00 is higher than all provided dates. Data will be taken from the closest lower year.
2026-08-26 08:36:23.644 | INFO     | bw_timex.timex_lca:run:834 - Step 2/4: Calculating LCI...
2026-08-26 08:36:24.086 | INFO     | bw_timex.timex_lca:lci:1440 - Expanding matrices...
2026-08-26 08:36:24.103 | INFO     | bw_timex.timex_lca:lci:1459 - Calculating dynamic inventory...
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 2.24e+13)
  warnings.warn(msg, UmfpackWarning)
2026-08-26 08:36:28.021 | INFO     | bw_timex.timex_lca:run:843 - Step 3/4: Calculating static LCIA...
2026-08-26 08:36:28.023 | INFO     | bw_timex.timex_lca:run:862 - Step 4/4: Calculating dynamic LCIA...
2026-08-26 08:36:28.042 | INFO     | dynamic_characterization.dynamic_characterization:characterize:135 - No custom dynamic characterization functions provided. Using default dynamic             characterization functions. The flows that are characterized are based on the selection                of the initially chosen impact category.
2026-08-26 08:36:28.119 | INFO     | bw_timex.timex_lca:run:873 - TimexLCA.run() completed successfully.

In [9]:
comparison.summary[["label", "base_score", "dynamic_score", "runtime_s"]]

         label    base_score  dynamic_score  runtime_s
0  bought 2020  23029.209074   38710.383983  15.966528
1  bought 2025  23029.209074   31377.740939   5.043378
2  bought 2030  23029.209074   24105.658666   4.676812

Two options worth knowing for `compare()`: `keep_objects=True` keeps each `TimexLCA`
in `ComparisonResult.objects`, to dig into one result's timeline or dynamic
inventory afterwards; `on_error="record"` puts a failure in the row's `error`
column and carries on, instead of aborting a long unattended sweep.

### Compare different scenarios

Instead of comparing different purchase years, we could also compare different *scenarios*. Give
each settings object a different `scenario={...}` (say `SSP2-PkBudg650` against
`SSP2-NPi`).

> Note how the SSP-NPi scenario does not exist in our project at this time. By setting `create_missing=True`, the respective premise scenario databases are created on the fly (internally using the `ensure_scenario_databases` function shown above), without any futher work.

In [10]:
from dataclasses import replace

comparison = TimexLCA.compare(
    [
        replace(
            settings,
            scenario={
                "pathway": pathway,
                "iam_model": "remind-eu",
                "ecoinvent_version": "3.12",
                "system_model": "cutoff",
                "years": [2020, 2030, 2040],
            },
            create_missing=True,
            label=f"Pathway {pathway}",
        )
        for pathway in ("SSP2-PkBudg650", "SSP2-PkBudg1000")
    ]
)

2026-08-26 08:36:28.226 | INFO     | bw_timex.timex_lca:__init__:444 - Initializing TimexLCA object...
2026-08-26 08:36:28.232 | INFO     | bw_timex.scenario_builder:ensure_scenario_databases:366 - All 3 requested background vintage(s) already exist in this project. Nothing to build.
2026-08-26 08:36:28.235 | INFO     | bw_timex.timex_lca:__init__:533 - Calculating base LCA...
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 8.06e+12)
  warnings.warn(msg, UmfpackWarning)
2026-08-26 08:36:29.249 | INFO     | bw_timex.timex_lca:__init__:588 - Collecting node infos...
2026-08-26 08:36:29.294 | INFO     | bw_timex.timex_lca:__init__:603 - Loading node metadata from 4 database(s)...
2026-08-26 08:36:29.358 | INFO     | bw_timex.timex_lca:__init__:648 - TimexLCA initialized.
2026-08-26 08:36:29.359 | INFO     | bw_timex.timex_lca:compare:1022 - Comparison 1/2: Pathway SSP2-PkBudg650
2026-08-26 08:36:29.359 | INFO     | bw_timex.timex_lca:run:812 - Starting TimexLCA.run() pipeline...
2026-08-26 08:36:29.359 | INFO     | bw_timex.timex_lca:run:819 - Step 1/4: Building timeline...
2026-08-26 08:36:29.360 | INFO     | bw_timex.timex_lca:build_timeline:1251 - No edge filter function provided. Skipping all edges in background databases.
2026-08-26 08:36:33.714 | INFO     | bw_timex.timex_lca:build_timeline:1274 - Creating activity time mapping...
2026-08-26 08:36:33.805 | INFO     | bw_timex.timeline_builder:__init__:119 - Traversing supply chain graph...
2026-08-26 08:36:33.823 | INFO     | bw_timex.timeline_builder:build_timeline:190 - Building timeline...
2026-08-26 08:36:33.905 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:895 - Reference date 2041-01-01 00:00:00 is higher than all provided dates. Data will be taken from the closest lower year.
2026-08-26 08:36:33.909 | INFO     | bw_timex.timex_lca:run:834 - Step 2/4: Calculating LCI...
2026-08-26 08:36:34.309 | INFO     | bw_timex.timex_lca:lci:1440 - Expanding matrices...
2026-08-26 08:36:34.320 | INFO     | bw_timex.timex_lca:lci:1459 - Calculating dynamic inventory...
2026-08-26 08:36:36.495 | INFO     | bw_timex.timex_lca:run:843 - Step 3/4: Calculating static LCIA...
2026-08-26 08:36:36.498 | INFO     | bw_timex.timex_lca:run:862 - Step 4/4: Calculating dynamic LCIA...
2026-08-26 08:36:36.516 | INFO     | dynamic_characterization.dynamic_characterization:characterize:135 - No custom dynamic characterization functions provided. Using default dynamic             characterization functions. The flows that are characterized are based on the selection                of the initially chosen impact category.
2026-08-26 08:36:36.591 | INFO     | bw_timex.timex_lca:run:873 - TimexLCA.run() completed successfully.
2026-08-26 08:36:36.592 | INFO     | bw_timex.timex_lca:__init__:444 - Initializing TimexLCA object...
2026-08-26 08:36:36.592 | INFO     | bw_timex.scenario_builder:ensure_scenario_databases:380 - Building 3 background database(s) for year(s) [2020, 2030, 2040] with premise (remind-eu, SSP2-PkBudg1000, all sectors). Each is a full copy of ecoinvent, so expect tens of minutes and roughly 2-4 GB per year.

premise v.(2, 4, 9, 2)
+------------------------------------------------------------------+
| Warning                                                          |
+------------------------------------------------------------------+
| Because some of the scenarios can yield LCI databases            |
| containing net negative emission technologies (NET),             |
| it is advised to account for biogenic CO2 flows when calculating |
| Global Warming potential indicators.                             |
| `premise_gwp` provides characterization factors for such flows.  |
| It also provides factors for hydrogen emissions to air.          |
|                                                                  |
| Within your Brightway project:                                   |
| from premise_gwp import add_premise_gwp                          |
| add_premise_gwp()                                                |
+------------------------------------------------------------------+
+--------------------------------+----------------------------------+
| Utils functions                | Description                      |
+--------------------------------+----------------------------------+
| clear_cache()                  | Clears the cache folder. Useful  |
|                                | when updating `premise`or        |
|                                | encountering issues with         |
|                                | inventories.                     |
| get_regions_definition(model)  | Retrieves the list of countries  |
|                                | for each region of the model.    |
| ndb.NewDatabase(...)           | Generates a summary of the most  |
| ndb.generate_scenario_report() | important scenarios' variables.  |
+--------------------------------+----------------------------------+
Keep uncertainty data?
NewDatabase(..., keep_source_db_uncertainty=True), keep_imports_uncertainty=True)

Hide these messages?
NewDatabase(..., quiet=True)
- Extracting source database
- Extracting inventories
- Fetching IAM data
Found file: remind-eu_SSP2-PkBudg1000
Reading remind-eu_SSP2-PkBudg1000 as CSV file
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
+-------------------------------------------------------------+
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
+-------------------------------------------------------------+
Found file: remind-eu_SSP2-PkBudg1000
Reading remind-eu_SSP2-PkBudg1000 as CSV file
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
+-------------------------------------------------------------+
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
+-------------------------------------------------------------+
Found file: remind-eu_SSP2-PkBudg1000
Reading remind-eu_SSP2-PkBudg1000 as CSV file
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
+-------------------------------------------------------------+
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
+-------------------------------------------------------------+
Done!

Processing scenarios for all sectors: 100%|█| 3/3 [06:48<00:00, 136.21

Done!

Write new database(s) to Brightway.
Running core export checks...
Minor anomalies found: check the change report.

Brightway database written: ei_cutoff_3.12_remind-eu_SSP2-PkBudg1000_2020
Running core export checks...
Minor anomalies found: check the change report.

Brightway database written: ei_cutoff_3.12_remind-eu_SSP2-PkBudg1000_2030
Running core export checks...
Minor anomalies found: check the change report.

Brightway database written: ei_cutoff_3.12_remind-eu_SSP2-PkBudg1000_2040
Generate scenario report.
Report saved under /Users/timodiepers/Documents/Coding/bw_timex/notebooks/advanced/export/scenario_report.
Generate change report.
Report saved under /Users/timodiepers/Documents/Coding/bw_timex/notebooks/advanced/export/change reports/.

2026-08-26 08:47:43.677 | INFO     | bw_timex.scenario_builder:ensure_scenario_databases:424 - Built 3 background database(s).
2026-08-26 08:47:43.684 | INFO     | bw_timex.timex_lca:__init__:533 - Calculating base LCA...
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 8.06e+12)
  warnings.warn(msg, UmfpackWarning)
2026-08-26 08:47:44.888 | INFO     | bw_timex.timex_lca:__init__:578 - Foreground links into ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2020 which is not part of the requested background. Matching its processes into the requested vintages by (name, reference product, location).
2026-08-26 08:47:44.889 | INFO     | bw_timex.timex_lca:__init__:588 - Collecting node infos...
2026-08-26 08:47:44.946 | INFO     | bw_timex.timex_lca:__init__:603 - Loading node metadata from 5 database(s)...
2026-08-26 08:47:49.422 | INFO     | bw_timex.timex_lca:__init__:648 - TimexLCA initialized.
2026-08-26 08:47:49.423 | INFO     | bw_timex.timex_lca:compare:1022 - Comparison 2/2: Pathway SSP2-PkBudg1000
2026-08-26 08:47:49.423 | INFO     | bw_timex.timex_lca:run:812 - Starting TimexLCA.run() pipeline...
2026-08-26 08:47:49.424 | INFO     | bw_timex.timex_lca:run:819 - Step 1/4: Building timeline...
2026-08-26 08:47:49.426 | INFO     | bw_timex.timex_lca:build_timeline:1251 - No edge filter function provided. Skipping all edges in background databases.
2026-08-26 08:47:55.786 | INFO     | bw_timex.timex_lca:build_timeline:1274 - Creating activity time mapping...
2026-08-26 08:47:55.908 | INFO     | bw_timex.timeline_builder:__init__:119 - Traversing supply chain graph...
2026-08-26 08:47:55.929 | INFO     | bw_timex.timeline_builder:build_timeline:190 - Building timeline...
2026-08-26 08:47:56.036 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:895 - Reference date 2041-01-01 00:00:00 is higher than all provided dates. Data will be taken from the closest lower year.
2026-08-26 08:47:56.039 | INFO     | bw_timex.timex_lca:run:834 - Step 2/4: Calculating LCI...
2026-08-26 08:47:56.568 | INFO     | bw_timex.timex_lca:lci:1440 - Expanding matrices...
2026-08-26 08:47:56.581 | INFO     | bw_timex.timex_lca:lci:1459 - Calculating dynamic inventory...
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 5.44e+13)
  warnings.warn(msg, UmfpackWarning)
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 3.97e+12)
  warnings.warn(msg, UmfpackWarning)
2026-08-26 08:48:22.325 | INFO     | bw_timex.timex_lca:run:843 - Step 3/4: Calculating static LCIA...
2026-08-26 08:48:22.329 | INFO     | bw_timex.timex_lca:run:862 - Step 4/4: Calculating dynamic LCIA...
2026-08-26 08:48:22.354 | INFO     | dynamic_characterization.dynamic_characterization:characterize:135 - No custom dynamic characterization functions provided. Using default dynamic             characterization functions. The flows that are characterized are based on the selection                of the initially chosen impact category.
2026-08-26 08:48:22.433 | INFO     | bw_timex.timex_lca:run:873 - TimexLCA.run() completed successfully.

In [11]:
comparison.summary[["label", "base_score", "dynamic_score", "runtime_s"]]

                     label    base_score  dynamic_score  runtime_s
0   Pathway SSP2-PkBudg650  23029.209074   27329.168394   7.232549
1  Pathway SSP2-PkBudg1000  23029.209074   28883.301235  33.010445