# Comparing Scenarios on `premise` Data

`TimexLCASettings` holds everything one calculation needs - the demand, the
method, the background selection, and every timeline/LCI/LCIA option - so one
object is also the record of what was run. `TimexLCA(...).run()`
executes it, `run()` can be called again with overrides, and
`TimexLCA.compare()` runs a list of them into one table.

We follow that through on a real prospective background, from an empty
project to a scenario comparison: build ecoinvent 3.12 (cutoff) plus REMIND-EU databases for 2020-2040 with
[premise](https://github.com/polca/premise), point a small electric-vehicle
foreground at them, and compare EV impacts 1) depending on the year it is
bought and 2) depending on the scenario.

## Setting up the databases

We start totally from scratch, in am empty project:

In [1]:
import bw2data as bd

bd.projects.set_current("my_new_timex_project")
list(bd.databases)

['ecoinvent-3.12-biosphere',
 'ecoinvent-3.12-cutoff',
 'ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2020',
 'ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2030',
 'ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2040',
 'ei_cutoff_3.12_remind-eu_SSP2-PkBudg1000_2020',
 'ei_cutoff_3.12_remind-eu_SSP2-PkBudg1000_2030',
 'ei_cutoff_3.12_remind-eu_SSP2-PkBudg1000_2040',
 'foreground',
 'ei_cutoff_3.12_remind-eu_SSP2-NPi_2020',
 'ei_cutoff_3.12_remind-eu_SSP2-NPi_2030',
 'ei_cutoff_3.12_remind-eu_SSP2-NPi_2040']

We can download the ecoinvent database and create scenario-copies of it with `premise` through our `ensure_scenario_databases` helper function. Running this requires a premise key (to be asked from `premise` maintainers) and valid ecoinvent credentials. These can be set as environment variables (`PREMISE_KEY`, `ECOINVENT_USERNAME`, `ECOINVENT_PASSWORD`) or passed to the function directly.

In [3]:
from bw_timex import ensure_scenario_databases

database_dates = ensure_scenario_databases(
    {
        "iam_model": "remind-eu",
        "pathway": "SSP2-PkBudg650",
        "system_model": "cutoff",
        "ecoinvent_version": "3.12",
        "years": [2020, 2030, 2040],
    },
    # premise_key="dummy_premise_decryption_key",
    # ecoinvent_credentials=("dummy_user", "dummy_password"),
)

2026-08-25 08:34:48.395 | INFO     | bw_timex.scenario_builder:_resolve_source_database:289 - No database 'ecoinvent-3.12-cutoff' in this project. Importing ecoinvent 3.12 (cutoff) first; this takes a while and needs an ecoinvent licence.

08:34:51+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
Applying strategy: normalize_units
Applying strategy: drop_unspecified_subcategories
Applying strategy: ensure_categories_are_tuples
Applied 3 strategies in 0.00 seconds
Graph statistics for `ecoinvent-3.12-biosphere` importer:
9850 graph nodes:
	emission: 9477
	natural resource: 353
	inventory indicator: 15
	economic: 5
0 graph edges:
0 edges to the following databases:
0 unique unlinked edges (0 total):

100%|██████████| 9850/9850 [00:00<00:00, 39501.94it/s]

08:34:58+0200 [info     ] Vacuuming database

Created database: ecoinvent-3.12-biosphere
Extracting XML data from 26533 datasets
08:35:04+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:35:04+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:35:04+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:35:04+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:35:04+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:35:04+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:35:04+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:35:04+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:35:04+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:35:04+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
08:35:32+0200 [info     ] Extracted 26533 datasets in 32.73 seconds
Applying strategy: normalize_units
Applying strategy: update_ecoinvent_locations
Applying strategy: remove_zero_amount_coproducts
Applying strategy: remove_zero_amount_inputs_with_no_activity
Applying strategy: remove_unnamed_parameters
Applying strategy: es2_assign_only_product_with_amount_as_reference_product
Applying strategy: assign_single_product_as_activity
Applying strategy: create_composite_code
Applying strategy: drop_unspecified_subcategories
Applying strategy: fix_ecoinvent_flows_pre35
Applying strategy: drop_temporary_outdated_biosphere_flows
Applying strategy: link_biosphere_by_flow_uuid
Applying strategy: link_internal_technosphere_by_composite_code
Applying strategy: delete_exchanges_missing_activity
Applying strategy: delete_ghost_exchanges
Applying strategy: remove_uncertainty_from_negative_loss_exchanges
Applying strategy: fix_unreasonably_high_lognormal_uncertainties
Applying strategy: convert_activity_parameters_to_list
Applying strategy: add_cpc_classification_from_single_reference_product
Applying strategy: delete_none_synonyms
Applying strategy: update_social_flows_in_older_consequential
Applying strategy: set_lognormal_loc_value
Applied 22 strategies in 4.54 seconds
Graph statistics for `ecoinvent-3.12-cutoff` importer:
26533 graph nodes:
	process: 26533
892943 graph edges:
	biosphere: 553892
	technosphere: 312518
	production: 26533
892943 edges to the following databases:
	ecoinvent-3.12-biosphere: 553892
	ecoinvent-3.12-cutoff: 339051
0 unique unlinked edges (0 total):


08:35:37+0200 [warning  ] Not able to determine geocollections for all datasets. This database is not ready for regionalization.

100%|██████████| 26533/26533 [00:32<00:00, 814.28it/s]

08:36:10+0200 [info     ] Vacuuming database
Created database: ecoinvent-3.12-cutoff

2026-08-25 08:38:14.397 | INFO     | bw_timex.scenario_builder:ensure_scenario_databases:363 - Building 3 background database(s) for year(s) [2020, 2030, 2040] with premise (remind-eu, SSP2-PkBudg650, all sectors). Each is a full copy of ecoinvent, so expect tens of minutes and roughly 2-4 GB per year.
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/export.py:1589: SyntaxWarning: invalid escape sequence '\ '
  + "\ ".strip()
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/export.py:1612: SyntaxWarning: invalid escape sequence '\ '
  + "\ ".strip()

Cannot find the IAM scenario file at /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files/remind-eu_SSP2-PkBudg650. Will check online.
Cannot find the IAM scenario file at /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files/remind-eu_SSP2-PkBudg650. Will check online.
Cannot find the IAM scenario file at /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files/remind-eu_SSP2-PkBudg650. Will check online.
premise v.(2, 4, 9, 2)
+------------------------------------------------------------------+
| Warning                                                          |
+------------------------------------------------------------------+
| Because some of the scenarios can yield LCI databases            |
| containing net negative emission technologies (NET),             |
| it is advised to account for biogenic CO2 flows when calculating |
| Global Warming potential indicators.                             |
| `premise_gwp` provides characterization factors for such flows.  |
| It also provides factors for hydrogen emissions to air.          |
|                                                                  |
| Within your Brightway project:                                   |
| from premise_gwp import add_premise_gwp                          |
| add_premise_gwp()                                                |
+------------------------------------------------------------------+
+--------------------------------+----------------------------------+
| Utils functions                | Description                      |
+--------------------------------+----------------------------------+
| clear_cache()                  | Clears the cache folder. Useful  |
|                                | when updating `premise`or        |
|                                | encountering issues with         |
|                                | inventories.                     |
| get_regions_definition(model)  | Retrieves the list of countries  |
|                                | for each region of the model.    |
| ndb.NewDatabase(...)           | Generates a summary of the most  |
| ndb.generate_scenario_report() | important scenarios' variables.  |
+--------------------------------+----------------------------------+
Keep uncertainty data?
NewDatabase(..., keep_source_db_uncertainty=True), keep_imports_uncertainty=True)

Hide these messages?
NewDatabase(..., quiet=True)
- Extracting source database
- Extracting inventories
- Fetching IAM data
remind-eu_SSP2-PkBudg650.csv not found locally. Downloading...

remind-eu_SSP2-PkBudg650.csv: 22.9MB [00:02, 8.18MB/s]

remind-eu_SSP2-PkBudg650.csv downloaded successfully.
Reading remind-eu_SSP2-PkBudg650 as CSV file
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
+-------------------------------------------------------------+
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
+-------------------------------------------------------------+
Found file: remind-eu_SSP2-PkBudg650
Reading remind-eu_SSP2-PkBudg650 as CSV file
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
+-------------------------------------------------------------+
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
+-------------------------------------------------------------+
Found file: remind-eu_SSP2-PkBudg650
Reading remind-eu_SSP2-PkBudg650 as CSV file
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
+-------------------------------------------------------------+
The following variables are missing from the IAM file: /Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/premise/data/iam_output_files
+-------------------------------------------------------------+
|                           Variable                          |
+-------------------------------------------------------------+
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Biomass |
|   FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Fossil  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Fossil  |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Fossil   |
|  FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Hydrogen  |
| FE|w/o Non-energy Use|Industry|Chemicals|Liquids|+|Hydrogen |
|   FE|w/o Non-energy Use|Industry|Chemicals|Gases|+|Biomass  |
|  FE|w/o Non-energy Use|Industry|Chemicals|Solids|+|Biomass  |
+-------------------------------------------------------------+
Done!

Processing scenarios for all sectors: 100%|█| 3/3 [06:57<00:00, 139.29

Done!

Write new database(s) to Brightway.
Running core export checks...
Minor anomalies found: check the change report.

Brightway database written: ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2020
Running core export checks...
Minor anomalies found: check the change report.

Brightway database written: ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2030
Running core export checks...
Minor anomalies found: check the change report.

Brightway database written: ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2040
Generate scenario report.
Report saved under /Users/timodiepers/Documents/Coding/bw_timex/notebooks/advanced/export/scenario_report.
Generate change report.

2026-08-25 08:49:26.560 | INFO     | bw_timex.scenario_builder:ensure_scenario_databases:407 - Built 3 background database(s).

Report saved under /Users/timodiepers/Documents/Coding/bw_timex/notebooks/advanced/export/change reports/.

We now find the base ecoinvent database as well as the three time-specific premise databases in our project:

In [2]:
list(bd.databases)

['ecoinvent-3.12-biosphere',
 'ecoinvent-3.12-cutoff',
 'ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2020',
 'ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2030',
 'ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2040']

Next, we add a foreground database. We use the same electric vehicle example as in [this teaching notebook](../teaching/ev_walktrough_premise.ipynb), which we can set up like this:

In [ ]:
from bw_timex import create_electric_vehicle_example

create_electric_vehicle_example(
    background_database_name="ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2020"
)

2026-08-25 09:17:01.968 | INFO     | bw_timex.utils:add_temporal_distribution_to_exchange:670 - Added temporal distribution to exchange Exchange: 20000.0 kilowatt hour 'market group for electricity, low voltage' (kilowatt hour, GLO, None) to 'driving an electric vehicle' (pkm over ev lifetime, GLO, None).
2026-08-25 09:17:01.971 | INFO     | bw_timex.utils:add_temporal_distribution_to_exchange:670 - Added temporal distribution to exchange Exchange: -280 kilogram 'market for used Li-ion battery' (kilogram, GLO, None) to 'driving an electric vehicle' (pkm over ev lifetime, GLO, None).
2026-08-25 09:17:01.971 | INFO     | bw_timex.utils:create_electric_vehicle_example:1271 - Created electric vehicle example in database 'foreground'.

## Calculating a `TimexLCA` using `TimexLCASetting``

In [2]:
from bw_timex import TimexLCA, TimexLCASettings

settings = TimexLCASettings(
    demand = {("foreground", "driving"): 1},
    method = ("ecoinvent-3.12", "EF v3.1", "climate change", "global warming potential (GWP100)"),
    scenario={
        "iam_model": "remind-eu",
        "pathway": "SSP2-PkBudg650",
    },
    timeline={ # Settings normally going into .build_timeline()
        "starting_datetime": "2028-01-01",
        "graph_traversal": "bfs",
    },
    lci={}, # Settings normally going into .lci()
    lcia={  # Settings normally going into .static_lcia() or .dynamic_lcia()
        "metric": "GWP",
        "time_horizon": 100,
    },
)

In [ ]:
tlca = TimexLCA(settings).run()

print("Time-explicit impact:", tlca.dynamic_score, bd.methods[settings.method]["unit"])

Another run using the same `TimexLCA` object, overwriting the time horizon setting:

In [6]:
tlca.run(time_horizon=20) # same as tlca.run(lcia={"time_horizon": 20})
print("Time-explicit impact with time horizon 20:", tlca.dynamic_score, bd.methods[settings.method]["unit"])

2026-08-25 13:31:56.803 | INFO     | bw_timex.timex_lca:run:757 - Starting TimexLCA.run() pipeline...
2026-08-25 13:31:56.804 | INFO     | bw_timex.timex_lca:run:764 - Step 1/4: Building timeline...
2026-08-25 13:31:56.804 | INFO     | bw_timex.timex_lca:run:779 - Step 2/4: Calculating LCI...
2026-08-25 13:31:57.187 | INFO     | bw_timex.timex_lca:lci:1382 - Expanding matrices...
2026-08-25 13:31:57.199 | INFO     | bw_timex.timex_lca:lci:1401 - Calculating dynamic inventory...
2026-08-25 13:31:59.451 | INFO     | bw_timex.timex_lca:run:788 - Step 3/4: Calculating static LCIA...
2026-08-25 13:31:59.454 | INFO     | bw_timex.timex_lca:run:807 - Step 4/4: Calculating dynamic LCIA...
2026-08-25 13:31:59.473 | INFO     | dynamic_characterization.dynamic_characterization:characterize:126 - No custom dynamic characterization functions provided. Using default dynamic             characterization functions. The flows that are characterized are based on the selection                of the initially chosen impact category.
2026-08-25 13:31:59.551 | INFO     | bw_timex.timex_lca:run:818 - TimexLCA.run() completed successfully.

Time-explicit impact with time horizon 20: 31108.708243680674 kg CO2-Eq

## Several calculations: `compare()`

To compare different settings even more easily, use the `compare()` function, which takes a list of settings. It returns a `ComparisonResult`
whose `summary` holds one row each - the scores next to every setting that
produced them, so the table is its own record of what was run.

### Compare different purchasing years

In [41]:
from dataclasses import replace

comparison = TimexLCA.compare(
    [
        replace(settings, starting_datetime=f"{year}-06-01", label=f"bought {year}")
        for year in (2020, 2025, 2030)
    ]
)

2026-08-25 10:06:52.786 | INFO     | bw_timex.timex_lca:__init__:429 - Initializing TimexLCA object...
2026-08-25 10:06:52.791 | INFO     | bw_timex.timex_lca:__init__:516 - Calculating base LCA...
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 7.65e+12)
  warnings.warn(msg, UmfpackWarning)
2026-08-25 10:06:53.771 | INFO     | bw_timex.timex_lca:__init__:533 - Collecting node infos...
2026-08-25 10:06:53.818 | INFO     | bw_timex.timex_lca:__init__:545 - Loading node metadata from 4 database(s)...
2026-08-25 10:06:53.916 | INFO     | bw_timex.timex_lca:__init__:590 - TimexLCA initialized.
2026-08-25 10:06:53.916 | INFO     | bw_timex.timex_lca:compare:964 - Comparison 1/3: bought 2020
2026-08-25 10:06:53.917 | INFO     | bw_timex.timex_lca:run:754 - Starting TimexLCA.run() pipeline...
2026-08-25 10:06:53.917 | INFO     | bw_timex.timex_lca:run:761 - Step 1/4: Building timeline...
2026-08-25 10:06:53.917 | INFO     | bw_timex.timex_lca:build_timeline:1193 - No edge filter function provided. Skipping all edges in background databases.
2026-08-25 10:06:58.473 | INFO     | bw_timex.timex_lca:build_timeline:1214 - Creating activity time mapping...
2026-08-25 10:06:58.569 | INFO     | bw_timex.timeline_builder:__init__:112 - Traversing supply chain graph...
2026-08-25 10:06:58.587 | INFO     | bw_timex.timeline_builder:build_timeline:183 - Building timeline...
2026-08-25 10:06:58.657 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:808 - Reference date 2018-01-01 00:00:00 is lower than all provided dates. Data will be taken from the closest higher year.
2026-08-25 10:06:58.659 | INFO     | bw_timex.timex_lca:run:776 - Step 2/4: Calculating LCI...
2026-08-25 10:06:59.068 | INFO     | bw_timex.timex_lca:lci:1379 - Expanding matrices...
2026-08-25 10:06:59.079 | INFO     | bw_timex.timex_lca:lci:1398 - Calculating dynamic inventory...
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 1.01e+13)
  warnings.warn(msg, UmfpackWarning)
2026-08-25 10:07:08.655 | INFO     | bw_timex.timex_lca:run:785 - Step 3/4: Calculating static LCIA...
2026-08-25 10:07:08.659 | INFO     | bw_timex.timex_lca:run:804 - Step 4/4: Calculating dynamic LCIA...
2026-08-25 10:07:08.681 | INFO     | dynamic_characterization.dynamic_characterization:characterize:126 - No custom dynamic characterization functions provided. Using default dynamic             characterization functions. The flows that are characterized are based on the selection                of the initially chosen impact category.
2026-08-25 10:07:08.758 | INFO     | bw_timex.timex_lca:run:815 - TimexLCA.run() completed successfully.
2026-08-25 10:07:08.760 | INFO     | bw_timex.timex_lca:compare:964 - Comparison 2/3: bought 2025
2026-08-25 10:07:08.760 | INFO     | bw_timex.timex_lca:run:754 - Starting TimexLCA.run() pipeline...
2026-08-25 10:07:08.760 | INFO     | bw_timex.timex_lca:run:761 - Step 1/4: Building timeline...
2026-08-25 10:07:08.760 | INFO     | bw_timex.timex_lca:build_timeline:1193 - No edge filter function provided. Skipping all edges in background databases.
2026-08-25 10:07:08.761 | INFO     | bw_timex.timex_lca:build_timeline:1214 - Creating activity time mapping...
2026-08-25 10:07:08.842 | INFO     | bw_timex.timeline_builder:__init__:112 - Traversing supply chain graph...
2026-08-25 10:07:08.851 | INFO     | bw_timex.timeline_builder:build_timeline:183 - Building timeline...
2026-08-25 10:07:08.937 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:815 - Reference date 2041-01-01 00:00:00 is higher than all provided dates. Data will be taken from the closest lower year.
2026-08-25 10:07:08.939 | INFO     | bw_timex.timex_lca:run:776 - Step 2/4: Calculating LCI...
2026-08-25 10:07:09.519 | INFO     | bw_timex.timex_lca:lci:1379 - Expanding matrices...
2026-08-25 10:07:09.532 | INFO     | bw_timex.timex_lca:lci:1398 - Calculating dynamic inventory...
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 1.01e+13)
  warnings.warn(msg, UmfpackWarning)
2026-08-25 10:07:13.626 | INFO     | bw_timex.timex_lca:run:785 - Step 3/4: Calculating static LCIA...
2026-08-25 10:07:13.628 | INFO     | bw_timex.timex_lca:run:804 - Step 4/4: Calculating dynamic LCIA...
2026-08-25 10:07:13.648 | INFO     | dynamic_characterization.dynamic_characterization:characterize:126 - No custom dynamic characterization functions provided. Using default dynamic             characterization functions. The flows that are characterized are based on the selection                of the initially chosen impact category.
2026-08-25 10:07:13.733 | INFO     | bw_timex.timex_lca:run:815 - TimexLCA.run() completed successfully.
2026-08-25 10:07:13.735 | INFO     | bw_timex.timex_lca:compare:964 - Comparison 3/3: bought 2030
2026-08-25 10:07:13.735 | INFO     | bw_timex.timex_lca:run:754 - Starting TimexLCA.run() pipeline...
2026-08-25 10:07:13.735 | INFO     | bw_timex.timex_lca:run:761 - Step 1/4: Building timeline...
2026-08-25 10:07:13.736 | INFO     | bw_timex.timex_lca:build_timeline:1193 - No edge filter function provided. Skipping all edges in background databases.
2026-08-25 10:07:13.736 | INFO     | bw_timex.timex_lca:build_timeline:1214 - Creating activity time mapping...
2026-08-25 10:07:13.848 | INFO     | bw_timex.timeline_builder:__init__:112 - Traversing supply chain graph...
2026-08-25 10:07:13.859 | INFO     | bw_timex.timeline_builder:build_timeline:183 - Building timeline...
2026-08-25 10:07:13.932 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:815 - Reference date 2041-01-01 00:00:00 is higher than all provided dates. Data will be taken from the closest lower year.
2026-08-25 10:07:13.935 | INFO     | bw_timex.timex_lca:run:776 - Step 2/4: Calculating LCI...
2026-08-25 10:07:14.336 | INFO     | bw_timex.timex_lca:lci:1379 - Expanding matrices...
2026-08-25 10:07:14.348 | INFO     | bw_timex.timex_lca:lci:1398 - Calculating dynamic inventory...
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 1.01e+13)
  warnings.warn(msg, UmfpackWarning)
2026-08-25 10:07:18.629 | INFO     | bw_timex.timex_lca:run:785 - Step 3/4: Calculating static LCIA...
2026-08-25 10:07:18.633 | INFO     | bw_timex.timex_lca:run:804 - Step 4/4: Calculating dynamic LCIA...
2026-08-25 10:07:18.653 | INFO     | dynamic_characterization.dynamic_characterization:characterize:126 - No custom dynamic characterization functions provided. Using default dynamic             characterization functions. The flows that are characterized are based on the selection                of the initially chosen impact category.
2026-08-25 10:07:18.735 | INFO     | bw_timex.timex_lca:run:815 - TimexLCA.run() completed successfully.

In [50]:
comparison.summary[["label", "base_score", "dynamic_score", "runtime_s"]]

         label    base_score  dynamic_score  runtime_s
0  bought 2020  23029.208898   38710.383570  14.842982
1  bought 2025  23029.208898   31377.740579   4.974826
2  bought 2030  23029.208898   24105.658370   5.000868

Two options worth knowing for `compare()`: `keep_objects=True` keeps each `TimexLCA`
in `ComparisonResult.objects`, to dig into one result's timeline or dynamic
inventory afterwards; `on_error="record"` puts a failure in the row's `error`
column and carries on, instead of aborting a long unattended sweep.

### Compare different scenarios

Instead of comparing different purchase years, we could also compare different *scenarios*. Give
each settings object a different `scenario={...}` (say `SSP2-PkBudg650` against
`SSP2-NPi`).

> Note how the SSP-NPi scenario does not exist in our project at this time. By setting `create_missing=True`, the respective premise scenario databases are created on the fly (internally using the `ensure_scenario_databases` function shown above), without any futher work.

In [3]:
from dataclasses import replace

comparison = TimexLCA.compare(
    [
        replace(
            settings,
            scenario={
                "pathway": pathway,
                "iam_model": "remind-eu",
                "ecoinvent_version": "3.12",
                "system_model": "cutoff",
                "years": [2020, 2030, 2040],
            },
            create_missing=True,
            label=f"Pathway {pathway}",
        )
        for pathway in ("SSP2-PkBudg650", "SSP2-NPi")
    ]
)

2026-08-25 15:44:46.287 | INFO     | bw_timex.timex_lca:__init__:444 - Initializing TimexLCA object...
2026-08-25 15:44:46.288 | INFO     | bw_timex.scenario_builder:ensure_scenario_databases:366 - All 3 requested background vintage(s) already exist in this project. Nothing to build.
2026-08-25 15:44:46.293 | INFO     | bw_timex.timex_lca:__init__:533 - Calculating base LCA...
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 7.65e+12)
  warnings.warn(msg, UmfpackWarning)
2026-08-25 15:44:47.315 | INFO     | bw_timex.timex_lca:__init__:562 - Foreground links into ecoinvent-3.12-biosphere which is not part of the requested background. Matching its processes into the requested vintages by (name, reference product, location).
2026-08-25 15:44:47.316 | INFO     | bw_timex.timex_lca:__init__:572 - Collecting node infos...
2026-08-25 15:44:47.367 | INFO     | bw_timex.timex_lca:__init__:587 - Loading node metadata from 5 database(s)...
2026-08-25 15:44:52.061 | INFO     | bw_timex.timex_lca:__init__:632 - TimexLCA initialized.
2026-08-25 15:44:52.062 | INFO     | bw_timex.timex_lca:compare:1006 - Comparison 1/2: Pathway SSP2-PkBudg650
2026-08-25 15:44:52.062 | INFO     | bw_timex.timex_lca:run:796 - Starting TimexLCA.run() pipeline...
2026-08-25 15:44:52.062 | INFO     | bw_timex.timex_lca:run:803 - Step 1/4: Building timeline...
2026-08-25 15:44:52.063 | INFO     | bw_timex.timex_lca:build_timeline:1235 - No edge filter function provided. Skipping all edges in background databases.
2026-08-25 15:44:55.710 | INFO     | bw_timex.timex_lca:build_timeline:1258 - Creating activity time mapping...
2026-08-25 15:44:55.793 | INFO     | bw_timex.timeline_builder:__init__:119 - Traversing supply chain graph...
2026-08-25 15:44:55.815 | INFO     | bw_timex.timeline_builder:build_timeline:190 - Building timeline...
2026-08-25 15:44:55.922 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:822 - Reference date 2041-01-01 00:00:00 is higher than all provided dates. Data will be taken from the closest lower year.
2026-08-25 15:44:55.924 | INFO     | bw_timex.timex_lca:run:818 - Step 2/4: Calculating LCI...
2026-08-25 15:44:56.315 | INFO     | bw_timex.timex_lca:lci:1424 - Expanding matrices...
2026-08-25 15:44:56.325 | INFO     | bw_timex.timex_lca:lci:1443 - Calculating dynamic inventory...
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 1.01e+13)
  warnings.warn(msg, UmfpackWarning)
2026-08-25 15:45:20.261 | INFO     | bw_timex.timex_lca:run:827 - Step 3/4: Calculating static LCIA...
2026-08-25 15:45:20.405 | INFO     | bw_timex.timex_lca:run:846 - Step 4/4: Calculating dynamic LCIA...
2026-08-25 15:45:20.432 | INFO     | dynamic_characterization.dynamic_characterization:characterize:126 - No custom dynamic characterization functions provided. Using default dynamic             characterization functions. The flows that are characterized are based on the selection                of the initially chosen impact category.
2026-08-25 15:45:20.675 | INFO     | bw_timex.timex_lca:run:857 - TimexLCA.run() completed successfully.
2026-08-25 15:45:20.676 | INFO     | bw_timex.timex_lca:__init__:444 - Initializing TimexLCA object...
2026-08-25 15:45:20.676 | INFO     | bw_timex.scenario_builder:ensure_scenario_databases:366 - All 3 requested background vintage(s) already exist in this project. Nothing to build.
2026-08-25 15:45:20.677 | INFO     | bw_timex.timex_lca:__init__:533 - Calculating base LCA...
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 7.65e+12)
  warnings.warn(msg, UmfpackWarning)
2026-08-25 15:45:21.529 | INFO     | bw_timex.timex_lca:__init__:562 - Foreground links into ecoinvent-3.12-biosphere, ei_cutoff_3.12_remind-eu_SSP2-PkBudg650_2020 which are not part of the requested background. Matching its processes into the requested vintages by (name, reference product, location).
2026-08-25 15:45:21.529 | INFO     | bw_timex.timex_lca:__init__:572 - Collecting node infos...
2026-08-25 15:45:21.584 | INFO     | bw_timex.timex_lca:__init__:587 - Loading node metadata from 6 database(s)...
2026-08-25 15:45:29.776 | INFO     | bw_timex.timex_lca:__init__:632 - TimexLCA initialized.
2026-08-25 15:45:29.777 | INFO     | bw_timex.timex_lca:compare:1006 - Comparison 2/2: Pathway SSP2-NPi
2026-08-25 15:45:29.778 | INFO     | bw_timex.timex_lca:run:796 - Starting TimexLCA.run() pipeline...
2026-08-25 15:45:29.778 | INFO     | bw_timex.timex_lca:run:803 - Step 1/4: Building timeline...
2026-08-25 15:45:29.778 | INFO     | bw_timex.timex_lca:build_timeline:1235 - No edge filter function provided. Skipping all edges in background databases.
2026-08-25 15:45:41.024 | INFO     | bw_timex.timex_lca:build_timeline:1258 - Creating activity time mapping...
2026-08-25 15:45:41.175 | INFO     | bw_timex.timeline_builder:__init__:119 - Traversing supply chain graph...
2026-08-25 15:45:41.219 | INFO     | bw_timex.timeline_builder:build_timeline:190 - Building timeline...
2026-08-25 15:45:41.313 | INFO     | bw_timex.timeline_builder:get_weights_for_interpolation_between_nearest_years:822 - Reference date 2041-01-01 00:00:00 is higher than all provided dates. Data will be taken from the closest lower year.
2026-08-25 15:45:41.319 | INFO     | bw_timex.timex_lca:run:818 - Step 2/4: Calculating LCI...
2026-08-25 15:45:42.171 | INFO     | bw_timex.timex_lca:lci:1424 - Expanding matrices...
2026-08-25 15:45:42.182 | INFO     | bw_timex.timex_lca:lci:1443 - Calculating dynamic inventory...
/Users/timodiepers/Documents/Coding/bw_timex/.venv/lib/python3.12/site-packages/scikits/umfpack/umfpack.py:737: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 1.41e+13)
  warnings.warn(msg, UmfpackWarning)
2026-08-25 15:46:04.826 | INFO     | bw_timex.timex_lca:run:827 - Step 3/4: Calculating static LCIA...
2026-08-25 15:46:04.829 | INFO     | bw_timex.timex_lca:run:846 - Step 4/4: Calculating dynamic LCIA...
2026-08-25 15:46:04.852 | INFO     | dynamic_characterization.dynamic_characterization:characterize:126 - No custom dynamic characterization functions provided. Using default dynamic             characterization functions. The flows that are characterized are based on the selection                of the initially chosen impact category.
2026-08-25 15:46:04.928 | INFO     | bw_timex.timex_lca:run:857 - TimexLCA.run() completed successfully.

In [6]:
comparison.summary[["label", "base_score", "dynamic_score", "runtime_s"]]

                    label    base_score  dynamic_score  runtime_s
0  Pathway SSP2-PkBudg650  23029.208898   27329.168068  28.614023
1        Pathway SSP2-NPi  23029.208898   30616.723696  35.150980